"""update user/name length to 100

Revision ID: 5a9def4591c4
Revises: 845a270e5e19
Create Date: 2025-10-04 21:14:32.315279

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5a9def4591c4'
down_revision: Union[str, Sequence[str], None] = '845a270e5e19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'schedules',
        'id',
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        comment='時段 ID',
        existing_comment='諮詢時段 ID',
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        'schedules',
        'giver_id',
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        comment='Giver ID',
        existing_comment='Giver 使用者 ID',
        existing_nullable=False,
    )
    op.alter_column(
        'schedules',
        'taker_id',
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        comment='Taker ID，可為 NULL（表示 Giver 提供時段供 Taker 預約）',
        existing_comment='Taker 使用者 ID，可為 NULL（表示 Giver 提供時段供 Taker 預約）',
        existing_nullable=True,
    )
    op.alter_column(
        'schedules',
        'status',
        existing_type=mysql.ENUM(
            'DRAFT',
            'AVAILABLE',
            'PENDING',
            'ACCEPTED',
            'REJECTED',
            'CANCELLED',
            'COMPLETED',
            collation='utf8mb4_unicode_ci',
        ),
        comment='時段狀態（後端會根據操作者角色自動決定：GIVER→AVAILABLE，TAKER→PENDING，其他→DRAFT）',
        existing_comment='諮詢時段狀態',
        existing_nullable=False,
        existing_server_default=sa.text("'DRAFT'"),
    )
    op.alter_column(
        'schedules',
        'date',
        existing_type=sa.DATE(),
        comment='時段日期',
        existing_comment='日期',
        existing_nullable=False,
    )
    op.alter_column(
        'schedules',
        'note',
        existing_type=mysql.VARCHAR(
            charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255
        ),
        comment='備註',
        existing_comment='備註，可為空',
        existing_nullable=True,
    )
    op.alter_column(
        'schedules',
        'created_by',
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        comment='建立者的 ID，可為 NULL（表示系統自動建立）',
        existing_comment='建立者的使用者 ID，可為 NULL（表示系統自動建立）',
        existing_nullable=True,
    )
    op.alter_column(
        'schedules',
        'updated_by',
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        comment='最後更新者的 ID，可為 NULL（表示系統自動更新）',
        existing_comment='最後更新的使用者 ID，可為 NULL（表示系統自動更新）',
        existing_nullable=True,
    )
    op.alter_column(
        'schedules',
        'deleted_by',
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        comment='刪除者的 ID，可為 NULL（表示系統自動刪除）',
        existing_comment='刪除者的使用者 ID，可為 NULL（表示系統自動刪除）',
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'schedules',
        'deleted_by',
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        comment='刪除者的使用者 ID，可為 NULL（表示系統自動刪除）',
        existing_comment='刪除者的 ID，可為 NULL（表示系統自動刪除）',
        existing_nullable=True,
    )
    op.alter_column(
        'schedules',
        'updated_by',
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        comment='最後更新的使用者 ID，可為 NULL（表示系統自動更新）',
        existing_comment='最後更新者的 ID，可為 NULL（表示系統自動更新）',
        existing_nullable=True,
    )
    op.alter_column(
        'schedules',
        'created_by',
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        comment='建立者的使用者 ID，可為 NULL（表示系統自動建立）',
        existing_comment='建立者的 ID，可為 NULL（表示系統自動建立）',
        existing_nullable=True,
    )
    op.alter_column(
        'schedules',
        'note',
        existing_type=mysql.VARCHAR(
            charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255
        ),
        comment='備註，可為空',
        existing_comment='備註',
        existing_nullable=True,
    )
    op.alter_column(
        'schedules',
        'date',
        existing_type=sa.DATE(),
        comment='日期',
        existing_comment='時段日期',
        existing_nullable=False,
    )
    op.alter_column(
        'schedules',
        'status',
        existing_type=mysql.ENUM(
            'DRAFT',
            'AVAILABLE',
            'PENDING',
            'ACCEPTED',
            'REJECTED',
            'CANCELLED',
            'COMPLETED',
            collation='utf8mb4_unicode_ci',
        ),
        comment='諮詢時段狀態',
        existing_comment='時段狀態（後端會根據操作者角色自動決定：GIVER→AVAILABLE，TAKER→PENDING，其他→DRAFT）',
        existing_nullable=False,
        existing_server_default=sa.text("'DRAFT'"),
    )
    op.alter_column(
        'schedules',
        'taker_id',
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        comment='Taker 使用者 ID，可為 NULL（表示 Giver 提供時段供 Taker 預約）',
        existing_comment='Taker ID，可為 NULL（表示 Giver 提供時段供 Taker 預約）',
        existing_nullable=True,
    )
    op.alter_column(
        'schedules',
        'giver_id',
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        comment='Giver 使用者 ID',
        existing_comment='Giver ID',
        existing_nullable=False,
    )
    op.alter_column(
        'schedules',
        'id',
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        comment='諮詢時段 ID',
        existing_comment='時段 ID',
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
